# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  run:
    desc: Run the app in debug mode
    dir: app
    cmds:
      - flutter run -d chrome
  build-web:
    desc: Build web with version info
    dir: app
    cmds:
      - flutter build web --release --base-href /didit/ --dart-define="APP_VERSION=$(git rev-parse --short HEAD) ($(date -u '+%Y-%m-%d'))"
  build-android:
    desc: Build Android APK with version info
    dir: app
    cmds:
      - flutter build apk --release --dart-define="APP_VERSION=$(git rev-parse --short HEAD) ($(date -u '+%Y-%m-%d'))"
  build-ios:
    desc: Build iOS with version info
    dir: app
    cmds:
      - flutter build ios --release --dart-define="APP_VERSION=$(git rev-parse --short HEAD) ($(date -u '+%Y-%m-%d'))"
  test:
    desc: Run all tests
    dir: app
    cmds:
      - flutter test
  format:
    desc: Format Dart code and Prettier-supported project files
    cmds:
      - dart format app
      - npx prettier --write .
  gen-art:
    desc: Generate all platform icons and splash screens from logo source files
    dir: app
    cmds:
      - dart run flutter_launcher_icons
      - cp assets/logo/didit-logo.svg web/favicon.svg
      - cp assets/logo/didit-logo.png web/favicon.png
      - dart run flutter_native_splash:create
